spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waaw_dev?createDatabaseIfNotExist=true
    username: root
    password: Pragra2020
  mail:
    userName: customer.service@waaw.ca
    password: WaaW2022@CS

logging:
  config: classpath:log4j2-dev.yml

#########################################
#####    Security Configurations    #####
#########################################
security:
  un-auth-url-patterns: /api/*/unAuth/**, /api/unAuth/**, /test/**, /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, ${application.websocket.connection-endpoint}/**
  cors-allowed-origins: http://localhost:3000,http://127.0.0.1:5500,http://localhost:4200
  # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
  jwt-secret: YjE0OTg3YTEyM2YwY2YyNGJjYmZlYTUwNjJkZDQ0YzYxNmUwNjIyMGVkOTIxNTEyODA1M2I3Yjk0NTU5NmIyNjMwZTJiZTlmNjA0YTAyNGY3MzdjOGNlNzQ4OTQzNTAxYmJiM2VlYmRiZGE1YTM5NjhiNGEyNWE1YzA0YTY1MTI=
  jwt-default-token-validity-in-seconds: 1800
  jwt-remember-me-token-validity-in-seconds: 2592000

########################################
#####    Swagger Configurations    #####
########################################
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

##############################
#####    Azure Config    #####
##############################
azure:
  sms:
    end-point: https://waaw-sms.communication.azure.com
    key-credential: kEjXJz/2DRm7taUTcr9mPWcB3dOb+lyki8bvhyzjRA3Syi0bRDBLt6q67CuGW9C49TZT2vPBpUn3g2nFBsyaoA==
  blob:
    account-name: waawstorage
    account-key: KJY8QGES7Z3iCzNgj0Z6qt/Vkwm/mQkWsArWgtdyRyjAb3zSssF2dYCH30/MKKH1Leya+WfKM24c+AStNRaKQQ==
    payrollName: stage-payroll
    payrollKey: sp=racwdli&st=2023-02-16T15:15:26Z&se=2026-09-29T23:15:26Z&sip=0.0.0.0-245.245.245.245&sv=2021-06-08&sr=c&sig=CHq1MPZGUHiZAaF0n8mfUnXNLSa%2BRpwKYbp3FZcfENQ%3D
    attendanceName: stage-attendance
    attendanceKey: sp=racwdli&st=2023-02-17T01:32:10Z&se=2026-02-17T09:32:10Z&sip=0.0.0.0-255.255.255.255&sv=2021-06-08&sr=c&sig=9SwM633QWXeBouPVNFYMFByCrakxshhgJvh8vuW6iyk%3D
    holidayName: stage-holiday
    holidayKey: sp=racwdli&st=2023-02-16T22:10:05Z&se=2026-02-17T06:10:05Z&sip=0.0.0.0-255.255.255.255&sv=2021-06-08&sr=c&sig=IuK8I%2Bz6mz0l1ZPlGsLNDgmjMMn8jUye1sB3OHgPAYk%3D
    picturesName: stage-pictures
    picturesKey: sp=r&st=2023-02-16T22:21:19Z&se=2026-02-17T06:21:19Z&sip=0.0.0.0-255.255.255.255&sv=2021-06-08&sr=c&sig=HFSYu0%2FvfROAomH8bzNeh6VKK64%2F2HY9vQMhZqyX1%2B0%3D
  send-grid:
    sender-name: WaaW
    sender-email: customer.service@waaw.ca
    api-key: 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

#################################################
#####    Application specific properties    #####
#################################################
application:
  create-dummy-data-on-startup: true
  urls:
    hosted-ui: http://localhost:3000
    hosted-server: http://localhost:8080
  mail:
    ui-url: ${application.urls.hosted-ui}