spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waaw_dev?createDatabaseIfNotExist=true
    username: root
    password: java@123
  mail:
    userName: customer.service@waaw.ca
    password: WaaW2022@CS

logging:
  config: classpath:log4j2-dev.yml

#########################################
#####    Security Configurations    #####
#########################################
security:
  un-auth-url-patterns: /api/*/unAuth/**, /api/unAuth/**, /test/**, /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, ${application.websockets.connection-endpoint}/**
  cors-allowed-origins: http://localhost:3000,http://127.0.0.1:5500,http://localhost:4200
  # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
  jwt-secret: YjE0OTg3YTEyM2YwY2YyNGJjYmZlYTUwNjJkZDQ0YzYxNmUwNjIyMGVkOTIxNTEyODA1M2I3Yjk0NTU5NmIyNjMwZTJiZTlmNjA0YTAyNGY3MzdjOGNlNzQ4OTQzNTAxYmJiM2VlYmRiZGE1YTM5NjhiNGEyNWE1YzA0YTY1MTI=
  jwt-default-token-validity-in-seconds: 1800
  jwt-remember-me-token-validity-in-seconds: 2592000

########################################
#####    Swagger Configurations    #####
########################################
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

##############################
#####    Azure Config    #####
##############################
azure:
  sms:
    end-point: https://waaw-sms.communication.azure.com
    key-credential: kEjXJz/2DRm7taUTcr9mPWcB3dOb+lyki8bvhyzjRA3Syi0bRDBLt6q67CuGW9C49TZT2vPBpUn3g2nFBsyaoA==
  blob:
    payroll-name: development
    payroll-key: sp=racwdli&st=2023-04-06T12:49:52Z&se=2200-04-06T20:49:52Z&sv=2021-12-02&sr=c&sig=ayBl0rNCAJtgQHTe4hvsKmb8IyoAS6iPXHukwVcnkWs%3D
    attendance-name: development
